### ISSUE TITLE
Add UAB solver enhancements

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#118]
University Autonoma of Barcelona (UAB) has made enhancements to the conservation of mass solver in WindNinja to speed up computations and improve scalability by organizing the memory more efficiently.  They are adding the code to a test branch of WindNinja called UAB.  When this has been vetted by WindNinja developers it will be folded into the master branch.  At that time, we should give credit to UAB by adding these names to our "contributors" list on the WindNinja help and our web page:
Ana Cortés (ana.cortes@uab.es)
Gemma Sanjuan (gemma.sanjuan@caos.uab.es)
Nicolás Chiaraviglio (nicolas.chiaraviglio@uab.es)
Tomàs Margalef (tomas.margalef@uab.es)

Their organization name is:
High Performance Computing Applications for Science and Engineering, University Autonoma of Barcelona

**Comment by ksshannon** [comment]
Pull request has been submitted, I will merge and cmake-ify.

**Comment by nwagenbrenner** [comment]
I think we're ready to merge this into the master branch. We did a fair amount of testing and didn't find any problems. Speed up is around 10% for typical cell counts (fine, medium, coarse) and up to around 20% for higher cell counts (~37M).

**Comment by ksshannon** [comment]
Do we get the same exact answers (same file size, same numbers, etc.)

**Comment by nwagenbrenner** [comment]
I didn't do all of the testing myself, but for the cases I ran, yes. If there are specific things you think we should check off, maybe make a list, and I'll see that someone gets to it. Probably not a bad thing to do.

**Comment by jforthofer** [comment]
My guess is that, if everything works like I think, the answers should pretty much be the same since the convergence test hasn't changed.  There could be slight differences but they most likely should be many decimal places out.

**Comment by ksshannon** [comment]
@jforthofer, how are we going to handle external contributions?  This gets pretty crappy, since public domain doesn't exist in many countries.  Should we adopt a liberal (BSD 3 clause or the like) license for external contributions, and just get an email sent to windninja.support@gmail.com with some boiler plate that says the contributors agree to contribute under those terms?

I've adopted a three file system for this, AUTHORS being actual copyright holders (organization or people), CONTRIBUTORS being actual people, and CREDITS for the political and ethical credits.  The CONTRIBUTOR and AUTHOR files are just data, so we have lists of entities, the CREDITS will have OpenFOAM, RMRS, etc, like it currently does.  Anyone we want to explicitly give credit to (as mentioned for political, accounting, or ethical reasons).

Side note, we only have the source of EasyBMP, and I added a license for it explicitly.  I removed all the other license templates from LICENSE.

See license branch for changes.

/cc @nwagenbrenner

**Comment by jforthofer** [comment]
How about if we talk about this when you're in Missoula Kyle?

**Comment by ksshannon** [comment]
Sounds good.

**Comment by ksshannon** [comment]
Done.
