### ISSUE TITLE
Output filename wrong for CFD diurnal run

### ISSUE THREAD

**Issue by jforthofer** [firelab/windninja#132]
The output kmz filename for a diurnal CFD run is different than when you use the native solver.  The input speed and direction is missing from the name for the CFD run.  Example:

CFD run -> italy_05-02-2016_1258_121m.kmz
native run -> italy_270_5_05-02-2016_1258_139m.kmz

**Comment by nwagenbrenner** [comment]
Speed and direction aren't included in the filename because at this point it's actually a griddedInitialization (not a domainAverageInitialization). We'll have to get the input speed/direction info from the ninjafoam if we want that displayed in the output filename. I guess we can just set that manually like we do for some of the other parameters. This is going to get messy... especially if this initialization is used for other things later on (e.g., not just linking CFD-native solver runs).

**Comment by nwagenbrenner** [comment]
Fixed in a42457c.
