### ISSUE TITLE
Output file name has output resolution - not mesh resolution

### ISSUE THREAD

**Issue by rnleach** [firelab/windninja#175]
When you manually set the output resolution, that value is reflected in the output file name instead of the mesh resolution the CFD solver used.

**Comment by jforthofer** [comment]
Yeah, that's by design...  it's supposed to be the output resolution and not the mesh resolution.  I guess it's a historical reason why it's like this.  We used to have this standalone output file writer/resampler program called f2f.exe and it wasn't uncommon to write out different resolutions for a simulation back then, so that's why we put the output resolution into the filename.
If anyone else has any strong feelings about this, we could consider changing it...  but if not I'd say we'll just leave it.
Thanks for submitting the ticket Ryan.

**Comment by rnleach** [comment]
Sounds good, I just thought it might be convenient to have the mesh resolution in the file name since I was comparing the effects of different resolutions last night. But if you put everything in the file name it will get kind of long.

**Comment by jforthofer** [comment]
Yeah, it would be long and not too many users would be using that "feature"...
