### ISSUE TITLE
lcp files can't be fetched in the cli

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#237]
It looks like this was just never added to the cli?

**Comment by jforthofer** [comment]
I don't remember, but it's possible.  Kyle would know...

**Comment by jforthofer** [comment]
Is this needed to modify the mobile app backend to use lcp so vegetation doesn't need to be specified (among other uses)?

**Comment by nwagenbrenner** [comment]
No, but it's needed for the automated testing you suggested.

**Comment by jforthofer** [comment]
Copy.  In the app I suppose there would have to be a call to an exe or something that would clip out the domain from an on-disk lcp of the whole US and feed that to the cli run?

**Comment by ksshannon** [comment]
Potential fix for the LCP source in lcp-cli-fix

**Comment by ksshannon** [comment]
As far as the local LCP source on the mobile server, it can be done with the same mechanism as the SRTM data, although it requires an extra step because the lcp driver  doesn't support `Create()`.  So:
`gdalwarp -of VRT big_lcp_source.tif out.vrt`

`gdal_translate -of LCP out.vrt out.lcp`

I *think*.
