### ISSUE TITLE
Problems with DEM bounding box on Windows

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#287]
The bounding box isn't shaded anymore and the center point isn't visible so you can no longer click and drag the box around. Windows only.

**Comment by nwagenbrenner** [comment]
Chuck confirms he first noticed this about two weeks ago. There was a google maps API release on Feb 13, maybe it's related to this. Not sure why an API change would affect Windows and not Linux.

https://developers.google.com/maps/documentation/javascript/releases

It's like the rectangle options are being ignored. There is no rectangle outline (just the circles delineating the box), no fill, and no draggable center point.

**Comment by nwagenbrenner** [comment]
But we're using API version 3.5, so this can't be the issue. No idea what's going on.

**Comment by fspataro** [comment]
The windows/linux difference sort of makes sense as I doubt QtWebView is exactly the same build in both environments.... but I pulled the map.htm from the data folder and ran it locally in IE11, Edge, and Chrome on Windows.  The bounding box works fine in this case -- i see the missing the fill in the DEM dialog version.  

Couple of thoughts:  To make this map work locally in a browser I had to add my Google Maps API key.  Are you injecting that manually at runtime or skipping it?  Google won't load the map script without it now so maybe it's something along those lines. eg without the key you're not getting all the API code.  You could try adding &key=XXXX to the script embed.  

Otherwise is appears to be very specific to the QtWebView implementation.  Does it have a developer tools console or javascript debug engine?

**Comment by nwagenbrenner** [comment]
Thanks Fred. Yes, we use an API key at runtime. Yes, to enable the debugging console you can set Tools->Set Configuration Option->`ENABLE_QWEBINSPECTOR = ON`.

**Comment by fspataro** [comment]
Yeah, that helps....   Couple of things:

1. You're loading v3.5 specifically and the latest is v3.32  --- there's an error in poly.js on load and old-version warning in the console.  I modified the file not use a specific version and those go away.  Not sure if that's possible to use the latest overall but 3.5 is a loooooong way back.  

2. The polygon fill isn't fixed with the latest version but it does appear to be an error in marker.js

![image](https://user-images.githubusercontent.com/5933821/37057024-4d79b5bc-2143-11e8-8244-ed166b3519e5.png)

I don't see the bulls-eye center point so that's probably the culprit ... same issue when using the "click center point".

**Comment by fspataro** [comment]
That file is placemark_circle.png from maps.google.com but it doesn't appear to get downloaded in the Qt network trace:

![image](https://user-images.githubusercontent.com/5933821/37057502-d377ff6a-2144-11e8-9cf0-dd4848bbab1b.png)

**Comment by fspataro** [comment]
Well, that error message is from the marker but that's not the fill issue... if i remove the code that adds the marker, still no fill and no error messages... I can't get the script debugger to function so i put a whole bunch of console.log into the code and it all seems to be running fine, events and function run to end, objects look correctly populated, no unexpected breaks, etc  

I'm at a loss.  It appears to be something specifically with the way Google maps is drawing to the dom/canvas and this browser implementation on Windows.  It could easily be some patch MS has applied recently, they are doing a lot to sure up security holes.

**Comment by fspataro** [comment]
This is your issue:

https://stackoverflow.com/questions/49051124/python-google-map-javascript-api-this-d-bind-error-adding-marker-to-map

This embedded browser is basically not supported even with the older versions.

Looking at the script versions now, it appears they aren't even allowing you to download v3.5.  It overrides and pulls 3.30.  In that case both poly.js (where rect is located) and marker.js are throwing that bind error.

**Comment by fspataro** [comment]
Looks like nothing below v3.30 will load... everything I try below that automatically loads 3.30

![image](https://user-images.githubusercontent.com/5933821/37060837-bce19d7e-214e-11e8-9499-fdc71969ab5f.png)

**Comment by fspataro** [comment]
It looks like Qt has a component/module called QtWebEngine.  This seems to be about the same functionality as QtWebView but uses Chromium vs the older WebKit.  It might be as simple as using that control... 

Other options:
* Different web api - Leaflet or OpenLayers... you can still google for the base maps in those or MapBox 
* A specific Qt map control like MapBox or ArcGIS.  The licensing is a little odd but I think you'd qualify under the 'free' versions.

**Comment by rnleach** [comment]
I'm not sure if it is related or not, but in some cases the map freezes up and you cannot "drag" or "pull" on the map with a left mouse button click to recenter. The work around was to set the center lat-lon manually by entering the center point and bounding box size. I'm not sure if this should be a separate issue, but I figure if you plan on upgrading the map interface it will probably get fixed then.

**Comment by rnleach** [comment]
Another issue related to the map, sometimes the whole dialog freezes up and one of the box dimensions is reported as 0. The workaround for this was to drag and select a box immediately, then try to recenter. Again, I'm not sure if this should be a separate issue, but I figure if you plan on upgrading the map interface it will probably get fixed then.

**Comment by nwagenbrenner** [comment]
As of today, the DEM downloader widget is completely broken. When the widget is launched you get a darkened map with a message that says "This page can't load Google Maps correctly." If you click on "Do you own this website" you can see the reason is because we don't have billing enabled.

**Comment by nwagenbrenner** [comment]
Now working from related issue #242
