### ISSUE TITLE
Add wrfout test data

### ISSUE THREAD

**Issue by ksshannon** [firelab/windninja#292]
If possible, add a small wrfout test file for automated testing.  Let me know if this is possible.  I found a small fix I'd like to commit, but don't want to break wrfSurfInitialization

**Comment by nwagenbrenner** [comment]
The smallest wrfout file I have on hand is 10s of MB (for the small BSB domain). Not sure we want to start putting files of that size in the repo? I put it here https://weather.firelab.org/ninja/windninja/. Can we download this during the auto testing? Otherwise I can try to generate a smaller one at some point to include in the repo for testing.

**Comment by ksshannon** [comment]
That's what I thought.  How about we just download it for now, if we come across one, we'll grab it.  Thanks.

**Comment by nwagenbrenner** [comment]
There is one here for download for our use: https://ninjastorm.firelab.org/data/
