### ISSUE TITLE
Strategies for running real HRRR data for more than 18 hours

### ISSUE THREAD

**Issue by micahjohnson150** [firelab/windninja#318]
@ksshannon, we are trying to create WindNinja runs using HRRR. Our end goal is to run the real hours of HRRR for any amount of time. 

1. It seems we must trick windninja into thinking that the real hours are forecast hours. So I am thinking we will just rename the files so the last value is what is being index. Is this the correct thinking?

2. If we can do this file rename, is there going to be a limit on how many hours will be read in (e.g. 99 hours)? 

3. Another thought we had was is it better to perhaps merge these into a netcdf more like the wrf data instead of renaming .grb files?

Details:
wx_model_type =  NOMADS-HRRR-CONUS-3-KM

**Comment by ksshannon** [comment]
Micah,
Can you send me some example files?  I should be able to just relax some checks in nomads, and let it run.  It does make some assumptions on the filenames though.  I'll have to take a peek.

**Comment by micah-prime** [comment]
Hey Kyle,

What's the best way to get you that data?

**Comment by ksshannon** [comment]
How large are the files?  Maybe try send.firefox.com?

On Wed, Aug 29, 2018, at 09:29, Micah Sandusky wrote:
> Hey Kyle,
> 
> What's the best way to get you that data?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/firelab/windninja/issues/318#issuecomment-416994903


-- 
Kyle

**Comment by ksshannon** [comment]
Actually, I just need a two, and a definition of how the files are named.

**Comment by micah-prime** [comment]
Thanks for the tip on send.firefox.com. Here are 3 files: https://send.firefox.com/download/01bd908ff1/#mzpzNTFo5TOW1TzcyaPwRw
 
I tried running WindNinja with these files through the cli and it seemed like it would work. It gave me 3 hours it would run, presumably based on the time stamp within the file.

The problem I'm seeing is that we store the hrrr grib files as the full CONUS. This seems to mean that the simulations will take way too long because it is trying to initialize with the full CONUS wind fields. 

Here is my current plan of attack:

I will write a python routine based off our current grib reader that writes to a NetCDF with the cropped domain and the correct variables. Then I will use that file to run the WindNinja simulation. 

Do you see any problems with this game plan or a slicker way of approaching this?

**Comment by micah-prime** [comment]
@ksshannon I've worked with this a bit more, and the grib2 files are very inflexible when it comes to modification. From what I can tell, WindNinja expects the grib2 files from HRRR, so cropping and copying the data to a NetCDF may not get me anything that runs. 

So my follow up question is, would it be possible to crop the input extent within WindNinja so that the entire CONUS grib2 file could be given and WindNinja would only initialize with the extent that it needs?

**Comment by ksshannon** [comment]
Micah,

I think I can pull this off.  Can you resend the files, so I can test it?

On Fri, Sep 28, 2018, at 14:24, Micah Sandusky wrote:
> @ksshannon I was able to crop the grib files using the wgrib2 utility so 
> that we have files of a reasonable size. This means we're renaming the 
> files, so the naming convention is not quite as important.
> 
> What I would like is to be able to run:
> hrrr.t00z.wrfsfcf00.grib2
> hrrr.t01z.wrfsfcf00.grib2
> 
> so that we could stay consistent with the original naming convention. 
> Currently we have to run:
> hrrr.t00z.wrfsfcf00.grib2
> hrrr.t00z.wrfsfcf01.grib2
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/firelab/windninja/issues/318#issuecomment-425555683


-- 
Kyle

**Comment by micah-prime** [comment]
@ksshannon 
Great! Here are some files and a dem.

https://send.firefox.com/download/2814d360b0/#5EkRZOELyatNChY-ZQGwrA

**Comment by ksshannon** [comment]
Well, the good news is this already works.  The bad news is I'm not sure if something gets lost in the naming stuff.  I unzipped dropped your files into a directory structure like:

```
$ tree
.
├── tuol.asc
├── tuol.prj
└── wx
    ├── hrrr.t00z.wrfsfcf00.grib2
    ├── hrrr.t01z.wrfsfcf00.grib2
    └── hrrr.t02z.wrfsfcf00.grib2
```

Then went into that directory and ran WindNinja_cli with this config file:

```
num_threads                     = 1
elevation_file                  = ./tuol.asc
initialization_method           = wxModelInitialization
time_zone                       = America/Denver
forecast_filename               = ./wx
output_wind_height              = 20.0
units_output_wind_height        = ft
vegetation                      = trees
diurnal_winds                   = false
mesh_choice                     = coarse
units_mesh_resolution           = m
write_goog_output               = true
write_wx_model_goog_output      = true
```

And it ran.  Again, I need to make sure things are named correctly, but I think this will work out of the box.

**Comment by micah-prime** [comment]
Hey Kyle,

That is great! I think I must have tried running three consecutive files with 01 as the forecast hour, but if the files I just provided work then I think that means we're in business. Thanks!
