### ISSUE TITLE
sign code for Windows

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#326]
We got a heads up from the CIO that there may soon be an issue with Windows Defender preventing WindNinja installs if the application is not signed with a Code Signing Certificate. We should look into this. We might be able to try CAcert, which issues certificates for free:

http://www.cacert.org/

Maybe there are other free options? Or maybe @ksshannon knows more about this? I also submitted the WindNinja installer for a malware scan at the Windows Defender Security Intelligence portal as suggested by the CIO guy. It passed and, as I understand it, new definitions should be sent out (or maybe they have to be requested by the client, it wasn't totally clear) to Windows Defender.

**Comment by ksshannon** [comment]
I'll do a little research.

**Comment by ksshannon** [comment]
Well, cacert.org doesn't have a proper certificate for there site, so I'm inclined to not use them.  There were a few with substantially lower costs (~$50), but I have to check on them.  DigiCert is ~$500/year, and I don't think we want that.  What are other folks doing at the lab?  This seems like it's a little bigger than us.

**Comment by nwagenbrenner** [comment]
I'm not sure if anyone else at the lab has looked into this. @jforthofer recently had a discussion with a CIO person who suggested it might be necessary due to upcoming changes with Windows Defender. We could talk to @stubrittain about flammap I guess? Or maybe @bnordgren has heard something? Or should we just wait until it's a problem and go from there?

**Comment by stubrittain** [comment]
I think what the CIO is talking about is an Authenticode Certificate. It prevents all the warnings during install. cacert I believe is attempting to distribute x.509 certificates which are geared more towards ssl.

Second, this is a can of worms the CIO needs to get straight for government developers. Otherwise, they could end up with a contractor like me buying the certificate and the govt has lost control. 

I've seen this issue pop up every year or so for 15 years and quietly go away. In my mind, if it ever becomes a 'real' issue I will stop creating an install for the various programs and just provide a zip file with all of the binaries/data and let the user create icons if he/she wants. In fact I have done this for FireFamily Plus. Further, all binaries in a distribution are supposed to be signed (from what I understand), I'm not even sure it is legal to sign DLL's produced from Open Source code (e.g. GDAL), and I'm also not sure of the ethics/legality of signing public domain software.

Other than just ignoring the issue, I would have Jason talk to the CIO and ask for guidance. I suspect they are not prepared to answer for software produced by the firelab, or for Open Source and Public Domain code compiled into binaries. The Govt should provide their own authority to distribute certificates, make sure the certificates are available on all govt computers, and also make available to non-federal govt users. Or, they could just relax their security standards and allow users to install from "untrusted" sources, which is basically the way it is now.

**Comment by ksshannon** [comment]
@stubrittain, this all sounds good to me.  You're right, the responsibility can't be on us.  I say we just don't worry about it.

**Comment by bnordgren** [comment]
Just another reason not to use Windows. :)  The platform seems to be
designed to create problems which require spending more money (on a regular
schedule) to solve.

We have a wildcard SSL certificate for *.firelab.org because some
time-wasting genius decided that public websites containing no sensitive
info and not supporting logins needed to be encryped "for security". If you
can use it, you're welcome to.

**Comment by nwagenbrenner** [comment]
Thanks @stubrittain @bnordgren @ksshannon. Sounds like we should hold off on this until it's a problem and/or we get more direction/clarification.
