### ISSUE TITLE
WRF initialization fails due to an issue with the specified warp options

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#334]
Setting the warp options to NULL for now. Relevant valgrind output:

==8058== Invalid write of size 4
==8058==    at 0x8DFB2FB: GDALAutoCreateWarpedVRT (vrtwarped.cpp:143)
==8058==    by 0x9D52CC5: wrfSurfInitialization::setSurfaceGrids(WindNinjaInputs&, 
==8058== 
==8058== Process terminating with default action of signal 11 (SIGSEGV)
==8058==  Access not within mapped region at address 0x0
==8058==    at 0x8DFB2FB: GDALAutoCreateWarpedVRT (vrtwarped.cpp:143)

**Comment by latwood** [comment]
This might be related to using a newer version of gdal. When I originally
tried to do the wrf stuff for WRF-WindNinja-FarsiteScript using the ideas
from WindNinja, I had similar error messages when using gdal 2.3.0. Only
way I could fix it was to use the older version of gdal.

I think the problem is one of the functions related to WarpedVRT has
changed the number, type, or order of inputs in gdal.

**Comment by nwagenbrenner** [comment]
My tests were on GDAL 2.2.2.

**Comment by latwood** [comment]
Right, what I'm saying is that the change to the function inputs and
outputs might have happened sometime between gdal 2.0.3 which was used
before, and gdal 2.3.0, not at gdal version 2.3.0. Anyhow I had a similar
error with gdal 2.3.0. My fix was to use the older version of gdal, which
is not an option now. I never figured out what the problem actually was,
but I thought it might be a change in the inputs to the function call.

**Comment by ksshannon** [comment]
You can also try enabling the vendored version of CreateWarpedVRT.  Enable NOMADS_INTERNAL_VRT in cmake, and I think the name is NomadsAutoCreateWarpedVRT that supports band mapping.
