### ISSUE TITLE
wmake error: 'Make' directory does not exist in

### ISSUE THREAD

**Issue by Saszalez** [firelab/windninja#338]
I have built Windninja and OpenFOAM with Intel compilers, on a Linux system (CentOS Linux release 7.6.1810). Windninja works perfectly. To be able to use OpenFOAM I am trying to build custom libraries and applications.

I copy all the contents of the `ninjafoam directory` in the OpenFOAM `applications directory`. When I execute wmake libso I get the following message:

```
wmake error: 'Make' directory does not exist in /my_openfoam_path/applications
```

**Comment by nwagenbrenner** [comment]
OpenFOAM installation issue resolved via email.

**Comment by roshan6890** [comment]
Hi! I'm facing the same problem. Could you please let me know how you resolved it? Thank you very much in advance. :)

**Comment by nwagenbrenner** [comment]
This was the last communication I received on this issue:

After searching a lot and reading many things, plus the help you gave me, I managed to use OpenFoam in parallel. I put you here the changes that I had to make.

I edited I edited OpenFOAM-2.2.0/etc/bashrc:

foamCompiler=system 
WM_COMPILER=Icc 
WM_MPLIB=INTELMPI

I added the following line:
export MPI_ROOT='/my_impi_path'

I edited the file OpenFOAM-2.2.0/etc/config/settings.sh:

In section 
Communications library

In the part of  INTELMPI, I changed:

_foamAddPath    $MPI_ARCH_PATH/bin64
_foamAddLib     $MPI_ARCH_PATH/lib64

I removed 64 because it was not in my system:

_foamAddPath    $MPI_ARCH_PATH/bin
_foamAddLib     $MPI_ARCH_PATH/lib

Finally, I edited the file OpenFOAM-2.2.0/wmake/rules/linux64Icc/mplibINTELMPI:

By default it is:

PFLAGS = -DMPICH_SKIP_MPICXX
PINC = -I$(MPI_ARCH_PATH)/include64
PLIBS = -L$(MPI_ARCH_PATH)/lib64 -lmpi

I edited it like this:

PFLAGS = -DMPICH_SKIP_MPICXX
PINC = -I$(MPI_ARCH_PATH)/include
PLIBS = -L$(MPI_ARCH_PATH)/lib -lmpi

With all these changes I could run the example case with 32 threads.

**Comment by nwagenbrenner** [comment]
Also, note that we use OpenFOAM version 8 on linux now. We still use OpenFOAM 2.2.x on Windows.

**Comment by roshan6890** [comment]
Hi Thank you very much for your response.
I am trying to install OpenFOAM-v2106. I tried to do like you have described. I tried to do like you described, but it does not work. (Maybe because I am doing something wrong, and I do not understand all those pieces of code since I am a beginner to Linux). Could you please make it descriptive or would you require any other input from my side? Could you please let me know? Thank you very much again. :)

**Comment by latwood** [comment]
That looks like an openfoam.com version, even if you got it compiled, the
file inputs and outputs will likely not match those uses by windninja
because Windninja uses openfoam.org version 8. After compiling that version
of openfoam, you would need to adjust Windninja code and foam files for the
different openfoam version, not an easy process even for someone
experienced with linux. Though most of the differences are internal to the
foam code, not to the result, or the case files. But the Boundary Condition
functions are a different matter, they had to be hand written and updated
for a given version of openfoam, you start to get into fluid dynamics
territory.


This link has info for how to do a Ubuntu apt install of openfoam 8, what
is currently done by build_depsh.sh in the windninja build process.
https://openfoam.org/download/8-ubuntu/
If you want to build it from scratch rather than an apt install, here are a
few links
https://openfoam.org/download/8-source/
https://openfoam.org/download/source/
These main compilation links are found under /archived versions/ on the
main openfoam.org website. May find another version of openfoam 8 that
could be helpful.
https://openfoam.org/download/archive/page/2/

Here are the old instructions for building Windninja with openfoam 2.2.0,
the most up to date method from the last time we built windninja with
openfoam from source. Note this was for a ubuntu 16.04 build.
https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Linux/507d3f7686933be983dbca53a299d9057fe3c166


Hope this helps.
