### ISSUE TITLE
Wind direction

### ISSUE THREAD

**Issue by ncubukcu** [firelab/windninja#389]
Hi 
I am a little puzzled by the image I attached below. This is the output of a domain averaged wind 6m/s and direction 0deg. By definition this has to be northerly wind. But because of the internal projection, the direction seems like it is the y axis of the domain rather than the true north.  I say that because directional values are very close to 0deg but what I see on this picture is more like 350deg (if I assume 0 is true north). Yes there is the effect of topography but in general wind direction seems like following the north of projected plain and not true north. Is that right? If that is the case then I need to make correction to lat lon every time I compare with station numbers. 

This is the Ascii (.asc) output option by the way. I recall in shapefile option there were different definition of wind direction but in .asc we only have one type. 
Thanks

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/53827558/96926887-30afd380-1484-11eb-824b-60b04e76fab8.png)

**Comment by nwagenbrenner** [comment]
The orientation of the domain is defined by the projection of the DEM. If you're projection doesn't preserve angles well, the longitude lines can be skewed and the WindNinja computational domain built from that DEM will be skewed. When you supply a wind direction to this skewed domain, the direction is also skewed from true north by that same amount since we assume the DEM is supplied with north up. The UTM projection is a good one to use since it preserves angles well (think the most you can be off within a UTM zone is ~4 degrees). This is the projection used by the DEMs downloaded by WindNinja. We have talked about this issue before and the possibility of trying to internally correct for projection errors, but haven't had a chance to work that yet. For now, the best option is to try and use UTM or manually adjust your input wind based on the error in your DEM projection. Hope this helps. Let us know if you have other questions about this issue.

**Comment by ncubukcu** [comment]
Thank you very much Natalie.
I was assuming that meteorological definition holds even if the DEM is supplied in different orientation.  As you said I could make an adjustment to the outputs I have ran so far and going forward I keep this detail in mind before supplying my input direction/s. I must say it would be safer to have internal adjustment  since this is very hard to notice especially for model or gridded initializations.
