### ISSUE TITLE
mass vs momentum solver

### ISSUE THREAD

**Issue by ncubukcu** [firelab/windninja#390]
Hi 
Is there a good publication or a study that shows the comparison of mass vs momentum solvers? I see really big difference  and not sure if it is expected. Here for example you see both with exact same model initialization (top figure is momentum bottom is mass solver).  
Thanks
nc
![Momentum](https://user-images.githubusercontent.com/53827558/99310997-d8bd8000-2829-11eb-9fd5-39c69eb1ad1f.PNG)
![Mass](https://user-images.githubusercontent.com/53827558/99311006-df4bf780-2829-11eb-960c-701ccd7ca79a.PNG)

**Comment by nwagenbrenner** [comment]
You can see here for a paper that describes/compares the two solvers.

https://www.researchgate.net/publication/336956614_Development_and_Evaluation_of_a_Reynolds-_Averaged_Navier-Stokes_Solver_in_WindNinja_for_Operational_Wildland_Fire_Applications

Your results look strange to me. How were the runs initialized? One thing to note with the momentum solver is that it's not able to utilize wx model data in the same way as the mass solver in wx model initializations. The mass solver is able to use the wx model forecast winds at every point in the domain to inform the initialization. The momentum solver is more limited in the way that it works and right now uses the domain average wx model wind field for the initialization. We hope to modify the momentum solver soon to allow it to use the wx model data in a way more similar to how it is done in the mass solver. I'm guessing this could be the issue you're seeing though. The predicted speeds are much lower in the momentum solver run and this could be due to the fact that the momentum solver is only able to utilize the domain-average wx model speed.

**Comment by ncubukcu** [comment]
Hi Natalie
Thank you so much for a quick response. I will take a look at the link tonight. You will see my cfg files below. So to go with what you are saying, I use gridded initialization with momentum option. Not sure if this is same as wx init but I was not aware of implicit domain average with this option.  Quite the opposite, I get  winds that are quite high compared to initial gridded field (the first image above). About twice as high I would say. Mass only solver actually predicts very similar magnitude compared to initial field.  But on the other hand I really like the details in the momentum solver predictions.  It seems as if there is a scaling issue I am missing with momentum option.  Thanks
Mass:
#Cfg File for W122N039
num_threads=4
elevation_file=CA/gridLcp/W122N039.lcp
initialization_method=griddedInitialization
input_speed_grid=W122N039/Input/W122N039-20161015:21_vel.asc
input_dir_grid=W122N039/Input/W122N039-20161015:21_ang.asc
input_speed_units=mps
input_wind_height=10
units_input_wind_height=m
time_zone=GMT
match_points=false
output_wind_height=20.0
output_speed_units=mph
units_output_wind_height=ft
output_path=OutputMass-2016101521
mesh_resolution=250.0
units_mesh_resolution=m
write_goog_output=true
goog_out_resolution=500
units_goog_out_resolution=m
write_shapefile_output=false
write_ascii_output=true

Momentum:
num_threads=4
elevation_file=CA/gridLcp/W122N039.lcp
initialization_method=griddedInitialization
input_speed_grid=W122N039/Input/W122N039-20161015:21_vel.asc
input_dir_grid=W122N039/Input/W122N039-20161015:21_ang.asc
input_speed_units=mps
input_wind_height=10
units_input_wind_height=m
time_zone=GMT
momentum_flag=true
number_of_iterations=100
match_points=false
output_wind_height=20.0
output_speed_units=mph
units_output_wind_height=ft
output_path=OutputMass-2016101521
mesh_resolution=250.0
units_mesh_resolution=m
write_goog_output=true
goog_out_resolution=500
units_goog_out_resolution=m
write_shapefile_output=false
write_ascii_output=true

**Comment by ncubukcu** [comment]
Hi Natalie
To make this issue simpler, I created a simple set in the attached zip. I ran this cfg for both COM and CFD solvers separately.   As I stated above, I see quiet the opposite case than what is published in the link you provided. Winds are almost twice higher in CFD case. You could run what I did by just turning these 2 lines on/off depending on which solver you want: 
momentum_flag=true
number_of_iterations=200
Thanks
[bundle.zip](https://github.com/firelab/windninja/files/5585046/bundle.zip)

**Comment by ncubukcu** [comment]
Hi Again
I went ahead and run series of cases with different resolution. Results:
1) GUI version produce very similar output compared to Input which is also similar to mass solver. 
2) Cli version produces resolution dependent output (see attached excel sheet)

My cli version:
WindNinja version: 3.6.0
SCM version: 0dbb3f3519feb84d930fc06db43170f80bbd2ba7
Release date: 2020/07/07
OpenMP enabled (64)

Thanks

![image](https://user-images.githubusercontent.com/53827558/100049426-45fe8180-2de5-11eb-8aad-fd6aaec71d76.png)

**Comment by nwagenbrenner** [comment]
@ncubukcu I'm looking into the test case you provided. I'll try to get back to you in the next day or so. Sorry for the delayed response.

**Comment by nwagenbrenner** [comment]
@ncubukcu Thanks for reporting this. There is an issue that arises when the mesh resolution becomes coarse in the momentum solver. For your case resolutions coarser than about 40 m start to show the issue. The momentum solver cannot handle skewed cells very well and so to avoid divergence issues we restrict the vertical size of the near-ground cells to be equal to the horizontal size of the near-ground cells. This means if you have a 40 m horizontal resolution, your near-wall ground cells will be 40 m tall. This is unfortunate as it would be ideal to have much better vertical resolution (e.g., the mass solver can handle somewhat skewed cells and so the vertical size of a 40 m wide cell could be maybe 0.5 m in the mass solver). You'll see there is some discussion of this limitation in that paper I linked to earlier. 

Another limitation in the momentum solver has to do with the post-processing step of interpolating the final 3-D wind field onto the user-specified height above ground (e.g., 10 m AGL in your case). Right now our sampling uses linear interpolation in the vertical, but we should us a logarithmic interpolation (this is what we do in the mass solver). The linear interpolation is not bad if you are sampling far from the surface, but the closer you get to the surface, the worse the linear interpolation is because in reality the wind follows a logarithmic profile above the surface.  

The combination of these two issues: 1. coarse vertical resolution and 2. linear interpolation in the vertical direction are causing the issues you are seeing (i.e., as the momentum solver mesh is coarsened, the output speeds increase). The cell skewness issue is not something we can easily fix, so we are stuck with tying the vertical cell height to the horizontal cell resolution at the ground for now. We have a plan to implement a logarithmic sampling scheme at the ground though which will mitigate this issue. I'll report back here once we have the post-processing interpolation issue resolved. In the meantime, you could try using higher resolution runs, which should give you better results. Thanks again for reporting this.

**Comment by ncubukcu** [comment]
Thank you very much Natalie..
Before I digest this two other question I would like to add:
1) Why is it that GUI version does not have this issue with momentum solver? Is it because in GUI we don't have the ability to pick our own resolution? An I guess If I try "fine" option in Cli I might get it working. 

2) While you mention wind  at user specified height, I must ask this question also. It is confusing to me (a meteorologist) that height is variable depending on the vegetation underneath. 10m for example should be always 10m above ground according to the WMO definition. If there is vegetation around the station there is usually a correction to 10m using power law.  The way I understand  from Ninja  documentations, the ninja output (say if 10m)  is above the vegetation but in your reply, your mentioned  10 m AGL. I just want to be sure what exactly I am getting from Ninja.  
Many thanks for your help!

**Comment by nwagenbrenner** [comment]
1. We recently added the ability to set a custom mesh resolution for the momentum solver, but haven't released the new version yet with that addition. We will do that later this week hopefully. From my testing the GUI and the CLI both have this problem if you decrease the resolution. 

2. Sorry, I shouldn't have said AGL, it is actually the height specified above the vegetation. We do it this way in WindNinja because most wildland fire applications require the wind above the canopy and so this just makes it simpler/more intuitive for fire managers.

We'll try to get a new release out later this week with the ability to set a custom mesh resolution for the momentum solver in the GUI as well as a fix for the logarithmic interpolation in the post-processing.

**Comment by ncubukcu** [comment]
Great.. Thanks Natalie

**Comment by nwagenbrenner** [comment]
Fixed with #392, #76, and #391.

**Comment by nwagenbrenner** [comment]
@ncubukcu We just released version 3.7.0 with the fixes mentioned above. Hopefully this helps with the issues you were seeing. Please keep us posted. Thanks.

**Comment by ncubukcu** [comment]
Thanks Natalie
Are we safe to say now that near ground treatment of wind is pretty much the same between the solvers other than the vertical size of cells (constrained in CFD)?  

One other thing you have mentioned was the initialization so could we clarify also that gridded initialization does not use domain avg wind in CFD to begin with?  Or is that the case? 
Thanks
