### ISSUE TITLE
Station data is fetched in the wrong time zone

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#412]
We are trying to make a request to SynopticLabs in UTC, but are making the request in local time.

**Comment by latwood** [comment]
Found an error in pointInitialization::getTimeList() where the user input is always in local time, but it is being used as utc time. This leads to improper input to the constructor call that generates the local time, as that form of the constructor expects utc time as input but the input is actually local time. The result is that anything that uses the times generated by this function is then off in time zone. https://github.com/firelab/windninja/blob/master/src/ninja/pointInitialization.cpp#L2550

This appears related to the fix for issue #386, it looks like we went from one constructor that used local time and an isDST boolean as input, to this one that uses utc time as input for that fix. Looks like we also lost the call to the storeTZAbbrev() function sometime since that issue as well.

Here's the list of constructors again: https://www.boost.org/doc/libs/1_49_0/doc/html/date_time/local_time.html#local_date_time_constr

The old constructor replaced when fixing issue #386 was the second constructor from the list, that used local time and an isDST boolean as input. The replacement constructor that is causing our troubles now is the first from the list, and expects utc time as input.



The third constructor is like the second constructor in that it takes in local time, but it avoids the need for the isDist bool. I've tried the third constructor with success at fixing the time zone problem, at least for downloading and running station data for my woolsey fire case in the gui. I don't know if use of the third constructor would fail when used on a broader set of test cases, like the one in issue #386. I also still need to make sure the fix is consistent for the cli and the gui, that there isn't more going on. Here is the fix to the above line, an example of the third constructor: https://github.com/firelab/windninja/blob/stationTimeZoneFix/src/ninja/pointInitialization.cpp#L2550.

Even if we just want to go back to the second constructor, or keep using the first constructor but convert to utc time another way, the isDST boolean shouldn't be a problem. The input time zone is already converted into a time_zone_ptr object, which has the function has_dst() that can be used to get the isDST boolean, and functions base_utc_offset() and dst_offset() that can be used to calculate the time conversion manually if needed. Here's the list of these functions: https://www.boost.org/doc/libs/1_49_0/doc/html/date_time/local_time.html#time_zone_base_accessors.

It looks like the old second constructor for local_time is being used in the other main time list generator function in pointInitialization, in generateSingleTimeObject(). So probably need to clean up the code a bit so the methods are consistent between the generateSingleTimeObject() and getTimeList() functions.
Here's the line for where that constructor is being used: https://github.com/firelab/windninja/blob/master/src/ninja/pointInitialization.cpp#L2652.

**Comment by nwagenbrenner** [comment]
@latwood I've committed the changes provided by @santiagoMonedero. The fix for this time zone issue can be incorporated into the master branch now. Once this is done, we should address the issues in #419 and #420.

**Comment by latwood** [comment]
Added changes provided by @santiagoMonedero with merge from master branch: commit 25d4402237f7c5689ddb80894de3938193939635. Still need to finish the time zone issue before checking out issues #419 and #420.
