### ISSUE TITLE
Add option to write binary VTK files 

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#416]
This will save disk space and improve simulation speed, particularly for the semi-lagrangian solver when we may be writing output for many timesteps. We can look at the binary STL writing for an example:

https://github.com/firelab/windninja/blob/master/src/ninja/stl_create.cpp

**Comment by latwood** [comment]
Found this document on vtk file formats useful: https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf
This stack overflow conversation on writing binary files with fwrite() vs fprintf() was also helpful: https://stackoverflow.com/questions/63765343/fprintf-writes-data-in-text-format-regardless-to-the-mode-i-use-in-fopen-to
Accidentally stumbled on this one when I thought my resulting binary vtk files should be working but couldn't figure out what was going on. Gave me the hint that the problem was LittleEndian vs BigEndian byte storage: https://stackoverflow.com/questions/10913666/error-writing-binary-vtk-files.

In the vtk file formats document, the first document shared in this comment, page 2 had the most helpful information for understanding how the format changed when converting from ASCII to BINARY format. Sounds like besides the LittleEndian vs BigEndian problem, there might also be cross compatibility issues with data sizes when using binary format.

More on the LittleEndian vs BigEndian problem: https://vtk.org/Wiki/VTK/Writing_VTK_files_using_python#.22legacy.22. I found this link when reading this other page: https://www.nag.com/blog/paraview-vtk-files-and-endianness.


Anyhow, the added functionality appears to work great, at least on my VM of Ubuntu. I didn't test read and write speed, but I did a mass conservation domain average run of 5 mph at 30 deg with no diurnal no stability on a coarse mesh of the missoula_valley.tif dem file, and saw the main vtk output file drop from 5.2 MB to 3.7 MB in size. The surface vtk file dropped from 143 kB to 93 kB in size.
