### ISSUE TITLE
Help needed building for windows

### ISSUE THREAD

**Issue by TAz00** [firelab/windninja#489]
Hi,

I've been trying to setup a build environment for Windows x64, but I'm running into a bunch of problems.

Following this guide 

https://github.com/firelab/windninja/wiki/Building-WindNinja-on-Windows-using-the-MSVC-compiler-and-gisinternals.com-dependencies

And these dependencies
```
Boost 1.46:
boost_date_time
boost_program_options
boost_test
NetCDF 4.1.1
GDAL 2.2.2
NetCDF support
PROJ.4 support
GEOS support
CURL support
Qt 4.8.5
QtGui
QtCore
QtNetwork/Phonon
QtWebKit
[OpenFOAM 2.2.x](https://github.com/OpenFOAM/OpenFOAM-2.2.x)
```

Microsoft no longer hosts the install for MSVC 2010 (Visual Studio 2010) so I cannot get the compiler version listed (from a trusted source).

Trying to download MSVC 2013 from https://visualstudio.microsoft.com/vs/older-downloads/ requires a license

MSVC 2014 - Fails to run bootstrap.bat for boost 1.46 
 
 `C:\Build\FromSource\src\x86\src\boost\tools\build\v2\engine\src>.\bootstrap\jam0 -f build.jam --toolset=vc7 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\\VC7\ " clean 

C:\Build\FromSource\src\x86\src\boost\tools\build\v2\engine\src>.\bootstrap\jam0 -f build.jam --toolset=vc7 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\\VC7\ "  `

It can however build the latest boost version 1.82, and I can finess cmake-gui to generate a Visual Studio 2015 project, but it fails to build.

This guide is also outdated, https://firelab.github.io/windninja/internal/buildwind.html and I cant find a 2010 msvc compiler from a trusted source.

So my question is, how is firelab building windows releases?

**Comment by nwagenbrenner** [comment]
We still use MSVC 2010 to build our Windows installer. We are in the process of migrating our Windows build to a modern MSVC compiler (or perhaps clang), but this requires updating some of our dependencies which is not trivial. The biggest one is that we need to migrate our GUI from Qt4 to Qt5. We are working on this, but it will still be some time before this work is complete (at least another year). In the meantime, if using MSVC 2010 is not an option, we have instructions for a minimal build (CLI and API only, so no Qt dependency) for compiling with MSVC 2019. See here:

https://github.com/firelab/windninja/wiki/Building-WindNinja-for-FlamMap-on-Windows-using-the-MSVC-compiler-and-gisinternals.com-dependencies

We do all of our development on Linux and only compile on Windows to generate our Windows installer, so this has been on the backburner for a while. Updating our Windows build has become a priority, however, due to our reliance on the unsupported MSVC 2010 compiler and the need to move to a modern build system. Hopefully we'll make some progress here over the coming months.

**Comment by bnordgren** [comment]
Another possibility [untested, but seems like it should work] is to compile the linux version under Windows Subsystem for Linux.

**Comment by latwood** [comment]
I've done it on the Windows Subsystem for Linux about 3 years ago. Has no
gui, and seems self contained separate from the windows system. At the time
the compiling also ran slower than on a VM of ubuntu, seemed to be because
of read and write time to disk for some odd reason.

Openfoam seems to recommend doing this if using Openfoam on Windows.
https://openfoam.org/download/windows/. Though as I had those problems with
not being able to use gui like stuff, just cli when I did this before, I am
not quite sure how paraview works with it? Yet that guide seems to imply
that paraview somehow works with it. But yeah, you basically pick what
version of Ubuntu for your subsystem of Linux, then it behaves just like
Ubuntu on a VM as a cli, though at the time I was not able to figure out
how to go from the cli to gui there was some idea of I believe x terminal
or something but I never worked it out.

**Comment by nwagenbrenner** [comment]
@TAz00 Please reach out if you have other questions about building on Windows. I'm going to go ahead and close this issue.
