### ISSUE TITLE
fetch_dem_exe issue

### ISSUE THREAD

**Issue by DanielSWx** [firelab/windninja#501]
Hi,

I'm currently trying to run the WindNinja_cli.exe and fetch_dem.exe files using Python. I believe I've gotten the WindNinja_cli.exe to work in my Python script, but I'm having issues with the fetch_dem.exe file. 

I've been using this code initially:

north = '40'
south = '39.6'
east = '-115'
west = '-115.4'
output_path = 'path/to/dem.tif
fetch_dem_exe = 'path/to/fetch_dem.exe'

fetch_dem_args = [fetch_dem_exe, '--bbox', north, east, south, west, '--src', 'us', output_path]

subprocess.run(fetch_dem_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

However, running the code winds up with this error:

CompletedProcess(args=['path/to/fetch_dem.exe', '--bbox', '40', '-115', '39.6', '-115.4', '--src', 'us', 'path/to/dem.tif'], returncode=4294967295, stdout='', stderr="ERROR 4: `/vsizip/vsicurl/http://dds.cr.usgs.gov/srtm/version2_1/SRTM1/Region_01/N39W115.hgt.zip/N39W115.hgt' does not exist in the file system, and is not recognized as a supported dataset name.\nERROR 1: Could not warp image, download failed.\nFailed to open a dataset\n")

Am I not calling the arguments correctly? Or is this more of an issue with the USGS database? It's entirely possible - if not likely - that the issue is on my end, so I wanted to ask this question here if it was ok! Any and all advice/suggestion would be greatly appreciated!

**Comment by nwagenbrenner** [comment]
@DanielSWx The SRTM data source (which is what `--src us` returns) is currently unavailable due to an API change on the SRTM server. More details here in #395. For now, you can use `--src lcp` data source if your domain is in the US or the `--src gmted` data source if your domain is outside of the US. The lcp is 30 m resolution and the gmted is 250 m resolution. Thanks for reporting this issue. I see our [tutorial ](https://weather.firelab.org/windninja/tutorials/fetch_dem_instructions.pdf)needs to be updated as it doesn't include the lcp source. You can see the full list of options by running `fetch_dem --help`.

**Comment by DanielSWx** [comment]
@nwagenbrenner ah gotcha, thanks so much for the quick reply and workaround! Appreciate all you guys do!!
