### ISSUE TITLE
refineWallLayer to < 5 m does not always work

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#58]
Shocker. We use refineWallLayer to split the near-ground layer cells until the final cell height is < 5 m. This often generates a mesh that passes all of the mesh checks, but sometimes not. We should maybe stop sooner or check the mesh log after each iteration and if a mesh check fails, undo (somehow...) the last iteration.

**Comment by jforthofer** [comment]
I wonder if this problem is related to the fact that these cells become very "pancake-like" here (large in the horizontal dimension, small in the vertical).  This could cause problems in the mesh checks and ultimately in the solver.  One possible solution might be to refine the near-ground cells in a different way, where the refinement also splits the cells in the horizontal directions, so the resulting cells won't be so pancake-like.  I don't know the best way to do this in OpenFOAM...

**Comment by nwagenbrenner** [comment]
Yes, I think this is the issue. I think we should use refineMesh instead.
This will let us refine a list of cells in multiple directions. I'm working
on how to generate a list of near-wall cells (a few layers near the ground).

**Comment by nwagenbrenner** [comment]
Fixed in b1b362f. We now use refineMesh and topoSet to refine cells near the ground.
