### ISSUE TITLE
problem adding windninja to the system path on windows

### ISSUE THREAD

**Issue by nwagenbrenner** [firelab/windninja#81]
A user got the following error when they checked the add to PATH box during installation: "Warning! PATH too long installer unable to modify PATH!" This was just reported, haven't looked into it at all.

**Comment by jforthofer** [comment]
I seem to remember something like this in the past...  Seems like Windows has a limit to the size of the string that holds PATH.  The problem is that each application appends a path to PATH by using a semicolon.  This user must have too many paths.  I'm sure a google search will turn up lots of results.  As a temporary work around for now they could try to edit their PATH to remove some unused ones to free up space in the string?  This would also confirm that this is the actual problem.

**Comment by nwagenbrenner** [comment]
They got around it. I'm closing this since it's not really a windninja issue.
